version: '3'
services: 
    web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules #use node modules from own container
            - .:/app #map outside current to app inside container
        stdin_open: true 
    tests: ## for test volume
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules #use node modules from own container
            - .:/app #map outside current to app inside container
        command: ["npm","run","test"] #override commands over dockerfile